version: '3.8'

services:
  stocksense-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://stocksense_admin:SecurePass2026@postgres:5432/stocksense_db?schema=public
      - JWT_SECRET=stocksense_jwt_secret_production_key_2026
      - PORT=4000
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: stocksense_admin
      POSTGRES_PASSWORD: SecurePass2026
      POSTGRES_DB: stocksense_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
